name: rpm
on:
  push:
    branches: [master]
    tags: ['*']
  workflow_dispatch:

jobs:
  build:
    runs-on: als-huge
    timeout-minutes: 30
    container:
      image: altlinux.space/alt-security/sisyphus/hasher:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          git config --global user.email "toxblh@altlinux.space"
          git config --global user.name "Toxblh"
          git add .
          gear-hsh --commit --no-sisyphus-check=gpg,packager

      - name: Remove debuginfo RPMs
        run: |
          find ~/hasher/repo -type f -name '*debuginfo*.rpm' -delete

      - name: Upload RPMs to the ALT package registry
        # SHA from alt-gnome/ReadySet
        uses: actions/upload-rpm-action@7ed97151a2a1f53a5b97f8a9f20778f771bbae59
        with:
          directory: ~/hasher/repo
          token: ${{ secrets.TOKEN }}
